version: '3.8'

services:
  be:
    build: ./be
    ports:
      - "8001:8001"
    depends_on:
      - postgresql
    networks:
      - app

  fe:
    build: ./fe
    ports:
      - "3000:3000"
    networks:
      - app

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: rahasia
      POSTGRES_USER: postgres
      POSTGRES_DB: database
      TZ: 'Asia/Jakarta'
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
    name: app