FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9 

# Set working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt ./

# Install dependencies
RUN pip install -r requirements.txt

# Copy your application code
COPY . .

# Expose port (adjust if needed)
EXPOSE 8000

# Command to run the application
CMD ["python", "appServer.py"]